version: '3'
services:
  hookah:
    container_name: hookah
    image: "felixfx/hookah"
    volumes: 
      - "/home/felix/src/herr-felix/hookah/handlers:/opt/hookah/handlers"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
    network_mode: host
