FROM docker

WORKDIR /root/build

RUN apk add make git moreutils --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.9/community

# TODO : Remove this
RUN apk add musl-dev go

COPY ./build.sh /

# TODO : replace by git clone in dockerfile
COPY ./demo ./demo

ENTRYPOINT ["/bin/sh", "/build.sh"]
